#ifndef FRIBIDI_CONFIG_H
#define FRIBIDI_CONFIG_H
#define FRIBIDI_VERSION              "1.0.15"
#define FRIBIDI_MAJOR_VERSION        1
#define FRIBIDI_MINOR_VERSION        0
#define FRIBIDI_MICRO_VERSION        15
#define FRIBIDI_INTERFACE_VERSION    4
#define FRIBIDI_INTERFACE_VERSION_MAJOR  4
#define FRIBIDI_INTERFACE_VERSION_MINOR  0
#define FRIBIDI_INTERFACE_VERSION_MICRO  0
#define FRIBIDI_INTERFACE_VERSION_STRING "4.0.0"
#define FRIBIDI_BINARY_VERSION       "3.0.0"
#define FRIBIDI_UNICODE_VERSION      "15.0.0"
#define FRIBIDI_UNICODE_CHARSET      1
#ifndef FRIBIDI_ENTRY
#define FRIBIDI_ENTRY
#endif
#endif
